name: Rust release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: "Install dioxus-cli"
        run: cargo install dioxus-cli

      - name: Bundle
        id: dioxus_bundle
        shell: bash
        run: |
          RAW_PATHS=$(dx bundle --desktop --json-output --verbose | tail -1 | jq -r '.json | fromjson | .BundleOutput.bundles []')
          echo "Discovered files:"
          echo "$RAW_PATHS"

          echo "PATHS_TO_RELEASE<<EOF" >> $GITHUB_OUTPUT
          echo "$RAW_PATHS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.dioxus_bundle.outputs.PATHS_TO_RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
